#!/usr/bin/env bash
# Transfers a file from our client to a server
# variables
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
f1

path_2_file=51
server_ip=52
username=53
ssh_key=54

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"server_ip":~/
