#!/usr/bin/env bash
# Configures a new ubuntu machine by install
# Installing nginx on web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World" > var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@thealchemist permanent;' /etc/nginx/sites-available/default
service nginx restart
